# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: npm i -g nx create-nx-workspace
    command: |
      mv .gitpod-template.yml create-nx-workspace.sh ../ &&
      rm -rf *.* LICENSE .git .gitpod.yml &&
      touch error.log &&
      clear && bash ../create-nx-workspace.sh &&
      rm ../create-nx-workspace.sh &&
      mv ../.gitpod-template.yml .gitpod.yml &&
      git init &&
      git add .gitpod.yml &&
      git commit -m "build(gitpod): add base configuration"
ports:
  - port: 4200
    onOpen: open-preview
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
